<a href="https://colab.research.google.com/github/TerteryanTatev/Machine-Learning-Algorithms/blob/main/Linear-Regression-Solver/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


data = {
    "area": [50, 60, 45, 80, 75, 55, 90, 40, 70, 65],
    "rooms": [2, 3, 2, 4, 3, 2, 4, 1, 3, 3],
    "floor": [3, 5, 2, 7, 6, 4, 8, 2, 5, 4],
    "distance": [5, 3, 7, 2, 4, 6, 1, 8, 3, 4],
    "price": [80, 120, 70, 150, 140, 90, 180, 60, 130, 125]
}

df = pd.DataFrame(data)

X = df.drop("price", axis=1).values
Y = df["price"].values

X = np.c_[np.ones(len(X)), X]

split = int(0.8 * len(X))

X_train = X[:split]
X_test = X[split:]

Y_train = Y[:split]
Y_test = Y[split:]

def mse(y, y_pred):
    return np.mean((y - y_pred) ** 2)

lambdas = [0.1, 1, 2]

results = []
print('A=', X_train.T @ X_train)
print('C=', X_train.T @ Y_train , '\n')
for lam in lambdas:
    I = np.eye(X_train.shape[1])
    I[0, 0] = 0
    W = np.linalg.inv(X_train.T @ X_train + 2* lam * I) @ (X_train.T @ Y_train)
    print(f'{lam} - {W}')

    Y_train_pred = X_train @ W
    Y_test_pred = X_test @ W


    train_mse = mse(Y_train, Y_train_pred)
    test_mse = mse(Y_test, Y_test_pred)

    print('\n y^train=', Y_train_pred, 'y^test=', Y_test_pred,'\n' )
    eps = np.sqrt((train_mse + test_mse) / 2)

    results.append((lam, train_mse, test_mse, eps))

for r in results:
    print(f"lamda={r[0]} Train MSE={r[1]:.3f} Test MSE={r[2]:.3f} eps={r[3]:.3f}")

A= [[8.0000e+00 4.9500e+02 2.1000e+01 3.7000e+01 3.6000e+01]
 [4.9500e+02 3.2875e+04 1.4250e+03 2.5700e+03 1.9450e+03]
 [2.1000e+01 1.4250e+03 6.3000e+01 1.1300e+02 7.7000e+01]
 [3.7000e+01 2.5700e+03 1.1300e+02 2.0700e+02 1.3000e+02]
 [3.6000e+01 1.9450e+03 7.7000e+01 1.3000e+02 2.0400e+02]]
C= [  890. 60400.  2640.  4790.  3310.] 

0.1 - [13.92064034  1.4778943  -0.14552147  4.24188372 -2.96712632]

 y^train= [ 85.41433192 114.46577351  67.84872407 155.32903177 137.90894539
  94.07856082 177.31698479  57.63764773] y^test= [129.24471649 114.64623496] 

1 - [ 2.7572517   1.79509385  0.36900233  1.79563876 -2.63380981]

 y^train= [ 85.46781617 112.64665415  69.42908854 155.14262083 138.73489087
  93.60511438 177.52300791  57.45080715] y^test= [130.59759266 117.19267483] 

2 - [-3.67921557  1.90804707  0.42480865  1.25493574 -2.23342166]

 y^train= [ 85.17045421 111.65244838  69.90843979 154.9814916  139.29466853
  93.73220365 177.55031972  57.70997412] y^test= [130.7329191  117.70432634

In [ ]:
data = {
    "x1": [30, 80, 45, 90, 50, 70, 35, 85, 60, 40],
    "x2": [2, 4, 2, 5, 3, 4, 2, 5, 3, 2],
    "x3": [0, 1, 0, 1, 1, 1, 0, 1, 1, 0],
    "x4": [8, 2, 6, 1, 5, 3, 7, 2, 4, 6],
    "y":  [0, 1, 0, 1, 0, 1, 0, 1, 1, 0]
}

df = pd.DataFrame(data)

split = int(0.8 * len(df))
train_df = df[:split]
test_df = df[split:]

X_train = train_df.drop("y", axis=1).values
y_train = train_df["y"].values.reshape(-1, 1)

X_test = test_df.drop("y", axis=1).values
y_test = test_df["y"].values.reshape(-1, 1)


X_train = np.c_[np.ones(len(X_train)), X_train]
X_test = np.c_[np.ones(len(X_test)), X_test]


def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def train_logistic(X, y, lr=0.1, epochs=500):
    W = np.zeros((X.shape[1], 1))

    for _ in range(epochs):
        y_pred = sigmoid(X @ W)

        gradient = X.T @ (y_pred - y) / len(y)
        W -= lr * gradient

    return W

W = train_logistic(X_train, y_train)

def predict(X, W):
    print('\n',X @ W,'\n')
    print(sigmoid(X @ W))
    return (sigmoid(X @ W) >= 0.5).astype(int)

y_train_pred = predict(X_train, W)
y_test_pred = predict(X_test, W)

def accuracy(y, y_pred):
    return np.mean(y == y_pred)

print( 'y^test',y_test_pred )
print("Train accuracy:", accuracy(y_train, y_train_pred))
print("Test accuracy:", accuracy(y_test, y_test_pred))

print("W:", W)


 [[-53.73332135]
 [ 24.00624121]
 [-28.80586811]
 [ 37.75767289]
 [-17.27178685]
 [ 10.24294302]
 [-42.56916629]
 [ 26.59351783]] 

[[4.61227340e-24]
 [1.00000000e+00]
 [3.08866235e-13]
 [1.00000000e+00]
 [3.15470146e-08]
 [9.99964393e-01]
 [3.25421304e-19]
 [1.00000000e+00]]

 [[ -3.50848866]
 [-31.40501123]] 

[[2.90716653e-02]
 [2.29602662e-14]]
y^test [[0]
 [0]]
Train accuracy: 1.0
Test accuracy: 0.5
W: [[-0.7843516 ]
 [ 0.51982862]
 [-0.0118665 ]
 [ 0.3817927 ]
 [-8.56501194]]
