<a href="https://colab.research.google.com/github/TerteryanTatev/Machine-Learning-Algorithms/blob/main/Hopfield-Associative-Network/hopfield_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random

x1 = np.array([1, 1, -1, 1])
x2 = np.array([-1, 1, 1, -1])
x3 = np.array([1, 1, -1, -1])

patterns = [x1, x2, x3]

n = len(x1)

W = np.zeros((n, n))

for p in patterns:
    W += np.outer(p, p)

np.fill_diagonal(W, 0)

print("W =")
print(W)

x = np.array([-1, 1, -1, -1])

print("\nInitial:", x)

for step in range(20):

    old_x = x.copy()

    indices = list(range(n))
    random.shuffle(indices)

    for i in indices:

        s = np.dot(W[i], x)

        if s >= 0:
            x[i] = 1
        else:
            x[i] = -1

    print(f"Step {step+1}: {x}")


    if np.array_equal(x, old_x):
        print("\nConverged")
        break

W =
[[ 0.  1. -3.  1.]
 [ 1.  0. -1. -1.]
 [-3. -1.  0. -1.]
 [ 1. -1. -1.  0.]]

Initial: [-1  1 -1 -1]
Step 1: [ 1  1 -1  1]
Step 2: [ 1  1 -1  1]

Converged
